services:
  backend:
    build: ./MER/Backend
    container_name: aerobase-backend
    ports:
      - "5001:5001"
    env_file:
      - ./MER/Backend/.env
    restart: unless-stopped
    networks:
      - aerobase

  frontend:
    build: ./MER/Fromend
    container_name: aerobase-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - aerobase

networks:
  aerobase:
    driver: bridge
